### ISSUE TITLE
Can you offer the scripts for the experiments in Sec.3?

### ISSUE THREAD

**Issue by cyberknight42** [rehg-lab/CLRec#1]
Thanks for your incredible work. 

Would you like to release the codes for the experiments in Sec.3? 

I tried to train an Auto-encoder on CIFAR100 for incremental learning without any memory, but I found the forgetting of AE was still serious.

Thanks.

**Comment by ngailapdi** [comment]
Hi,

Thank you for your question. For the Autoencoder we used SegNet as the backbone architecture. We will push the code for AE in the next couple of days and will let you know.

**Comment by ngailapdi** [comment]
The code for training autoencoder is updated at https://github.com/rehg-lab/CLRec/tree/master/auto_enc. Please follow the instructions in the README to train the model.
