### ISSUE TITLE
Program hangs at testing phase

### ISSUE THREAD

**Issue by e7mul** [rehg-lab/CLRec#2]
Hi, 

I tried to run the experiments from section 3 according to the instructions you specified here: https://github.com/rehg-lab/CLRec/tree/master/auto_enc 

However, after completing the first training process successfully the program hangs and cannot finish its job (~30 minutes with no output on terminal).

Below I copied the only output from the program I recieved.
```
perm_id: [53 25 76 44 35 86 48 36 91 18 66 54 49 30 50 57 60 98 33 74 79 51 28 75
 82 71 63 77 24  3 67 96 92 19 23 17 87  9 80 94 46 90 22 99 41 78 43  0
 88  4 89 72 45 12 37 11  1 70 15 62 93  6 26 58 14 85 21 10 56 68  7 38
 52 47 65 40 27 20 59 42 55 61 29  2 97 31 84 13 73 81 16  8 34  5 39 64
 95 32 69 83]
Files already downloaded and verified
(50000, 3, 32, 32)
Files already downloaded and verified
(10000, 3, 32, 32)
####### Test Process Running ########
[Test Process] Waiting on train process
[Test Process] train_counter :  0
[Test Process] test_counter :  0
####### Train Process Running ########
Args:  Namespace(batch_size=200, batch_size_test=200, d_order=False, img_size=32, init_lr=0.002, lexp_len=500, lrd=5, ncm=False, num_classes=1, num_epoch=250, num_iters=100, num_workers=8, one_gpu=False, outfile='results/autoenc_100cls_single.csv', rendered_img_size=300, resume=False, resume_outfile=None, save_all=False, save_all_dir=None, size_test=100, test_freq=1, total_classes=100, wd=1e-05)
Loading training examples for class index 0 , 53, at iteration 0
Current train set:  500
100%|█████████████████████████████████████████| 750/750 [00:49<00:00, 15.12it/s]
Model num classes : 1, 
Train Process Completed
```

 Do you have any idea what causes the issue? I've created conda env according to your instructions and just used your command to run the program. Thanks for any help!

**Comment by ngailapdi** [comment]
Hi, thank you for your interest in our work.

It looks like the training signal was killed (`Train Process Completed`). This means that the test process couldn't be called. This might happen if you are running another program on the machine or out of memory. My suggestion would be to kill unnecessary programs that utilize RAM and maybe try `--one_gpu` flag

**Comment by ngailapdi** [comment]
Hi @e7mul, just checking in if things work for you now. Can we close the issue if there is no further concern?

**Comment by e7mul** [comment]
Hi! Thanks for the response!

I looked at the memory more carefully but I guess this is not the issue of memory because during the execution I have plenty of free space there (I have 128GB RAM, and 2xRTX2080Ti). 

The exact moment when the program hangs is during the saving of _train_info.npz_, once I commented it out the program proceeds and hangs on line 270 `cond_var.acquire()` at `autoenc_incr_main.py`. 

Could it be any other issue than running out of memory?

**Comment by ngailapdi** [comment]
This sounds like it might be an issue with multithreading. Have you tried `--one_gpu`?

**Comment by e7mul** [comment]
Yes, I tried that but nothing changed. I also changed the value of test_freq to 5 and the program runs smoothly for 5 training loops but ultimately hangs at test, exactly on the line `test_model = dataQueue.get()`. I also noticed that the dataQueue is defined two times (line 129 and 200). Is it possible that this causes the problem?

**Comment by ngailapdi** [comment]
I believe defining `dataQueue` twice should not be an issue but you can try commenting one out. Maybe something like this thread would be helpful https://github.com/pytorch/pytorch/issues/4987
